//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaNajprej.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Mentor
    {
        public int MenId { get; set; }
        public string MenIme { get; set; }
        public string MenPriimek { get; set; }
        public byte[] MenSlika { get; set; }
        [DisplayName("Vloga")]
        public string MenVloga { get; set; }
        [DisplayName("Naziv")]
        public string MenNaziv { get; set; }
        [DisplayName("Ustanova")]
        public string MenUstanova { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    }
}
